version: 0.0
os: linux

files:             
  - source: /
    destination: /home/centos/webserver
hooks:
  ApplicationStop:
    - location: ./scripts/applicationStop.sh
      timeout: 180
      runas: centos
  BeforeInstall:
    - location: ./scripts/beforeInstall.sh
      timeout: 180
      runas: centos
  AfterInstall:
    - location: ./scripts/afterInstall.sh
      timeout: 180
      runas: centos

